<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->siteParam('core-site-title'))->setSeparator($this->siteParam('core-site-title-sep'))->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

		<?php $this
			->prependCSS("/css/style.less")
			->prependCSS("/atp-core/css/redmond/jquery-ui-1.10.3.custom.min.css")
		?>
        <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))?>

		<?php $this
			->prependJs("/atp-core/js/atp-template.js")
			->prependJs("/atp-core/js/mustache.js")
			->prependJs("/atp-core/js/jquery.elastic.source.js")
			->prependJs("/atp-core/js/jquery-ui-1.10.3.custom.min.js")
			->prependJs("/atp-core/js/jquery-1.10.2.min.js")
		?>
        <?=$this->headScript()?>

    </head>
    <body>
		<div id="page">
			<main>
				<?php echo $this->content; ?>
			</main>
		</div>
    </body>
</html>
